// src/helpers/ourFeatures.ts

export const featuresArr = [
  {
    title: "AI-Powered Learning",
    heading: "Personalized Roadmaps",
    avatar: "personalisedRoadmap.png",
    content: "Experience customized learning paths generated by AI, tailored to your goals and skill level. Our platform adapts to your unique learning journey."
  },
  {
    title: "Progress Tracking",
    heading: "Visual Progress",
    avatar: "progress.png",
    content: "Track your learning journey with interactive visualizations. Watch your progress grow with our beautiful zig-zag roadmap view and completion indicators."
  },
  {
    title: "Resource Integration",
    heading: "Curated Resources",
    avatar: "resourceIntegration.png",
    content: "Access hand-picked learning resources for each topic. Every step of your roadmap comes with quality documentation, tutorials, and references."
  },
  {
    title: "Timeline View",
    heading: "Structured Learning",
    avatar: "timeline.png",
    content: "Navigate your learning path with our intuitive timeline view. Break down complex topics into manageable subtopics and track completion."
  },
  {
    title: "Task Management",
    heading: "Stay Organized",
    avatar: "tasks.png",
    content: "Manage your learning tasks effectively. Mark topics as complete, track duration estimates, and maintain steady progress towards your goals."
  },
  {
    title: "Community Learning",
    heading: "Learn Together",
    avatar: "community.png",
    content: "Join a community of learners following similar paths. Share progress, exchange tips, and stay motivated throughout your learning journey."
  }
];
